# see https://symfony.com/doc/current/reference/configuration/framework.html

framework:
    secret: '%env(APP_SECRET)%'
    default_locale: 'en'

    # Note that the session will be started ONLY if you read or write from it.
    session:
        enabled: true
        handler_id: '%env(resolve:DATABASE_URL)%'
        cookie_secure: auto
        cookie_samesite: lax
        save_path: '%kernel.project_dir%/var/sessions'
    
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-proto', 'x-forwarded-host', 'x-forwarded-port']

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
